# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.

[package]
name = "sha256sum"
version = "0.1.0"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/RustCrypto/hashes"
edition = "2021"

[dependencies]
sha2 = "0.8.1"
